data:
  batch_size: 32
  class_mapping:
    ADI: 0
    BACK: 1
    DEB: 2
    LYM: 3
    MUC: 4
    MUS: 5
    NORM: 6
    STR: 7
    TUM: 8
  dataset_type: StandardImageDataset
  num_workers: 3
  suffle_test: false
  suffle_train: false
  test_dir: datasets/final/CRC-VAL-HE-7K-splitted/test
  train_dir: datasets/final/CRC-VAL-HE-7K-splitted/train
logging:
  log_file: ./logs.txt
  log_level: INFO
metric_logging:
  tool: txt
model:
  checkpoint_path: ''
  experiment_name: dinov2_CRC-VAL-HE-7K-splitted
  load_checkpoint: false
  model_name: dinov2_vitl14
  name: dinov2
  num_classes: 9
  pretrained: true
output:
  model_dir: ./artifacts/CRC-VAL-HE-7K-splitted
  results_dir: ./local_experiments/CRC-VAL-HE-7K-splitted
testing:
  embeddings_path: ./artifacts/CRC-VAL-HE-7K-splitted/embeddings_dinov2
  embeddings_save_path: ./artifacts/CRC-VAL-HE-7K-splitted/embeddings_dinov2
  list_of_metrics:
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: map@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: precision@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: recall@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: accuracy@k
  load_embeddings: false
  pipeline: default
  save_embeddings: true
transform:
  normalize:
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  resize:
  - 224
  - 224
  to_tensor: true
