# Paths and directories for training and testing data
data:
  dataset_type: StandardImageDataset    # Specify the dataset type (e.g., terumo, etc.)
  train_dir: datasets/final/CRC-VAL-HE-7K-splitted/train
  test_dir: datasets/final/CRC-VAL-HE-7K-splitted/test
  class_mapping: {ADI: 0, BACK: 1, DEB: 2, LYM: 3, MUC: 4, MUS: 5, NORM: 6, STR: 7,
    TUM: 8}
  batch_size: 32
  num_workers: 3  # Number of workers to load the data
  suffle_test: false
  suffle_train: false

# Transformation configuration for image preprocessing
transform:
  resize: [224, 224]  # Resize images to 224x224
  normalize:
    mean: [0.485, 0.456, 0.406]  # Normalize mean for ImageNet
    std: [0.229, 0.224, 0.225]   # Normalize std for ImageNet
  to_tensor: true  # Convert to tensor (default is true)

# Model configuration
model:
  name: resnet_fsl      # Example: You can set it to resnet18, resnet34, etc.
  experiment_name: resnet_fsl_CRC-VAL-HE-7K-splitted # Name of the experiment
  pretrained: true  # Use pre-trained weights
  num_classes: 9  # Number of classes in the dataset
  load_checkpoint: true   # Load a pre-trained model checkpoint
  checkpoint_path: 
    artifacts/glomerulo/resnet_fsl_glomerulo_resnet_fsl_2025-04-20_04-43-03_checkpoint.pth # Path to the model checkpoint
  model_name: resnet50                   # Specify the ViT model name


testing:
  pipeline: default    # The pipeline to run (e.g., default, retrieval, etc.)
  load_embeddings: false  # Load embeddings from disk
  embeddings_path: ./artifacts/CRC-VAL-HE-7K-splitted/embeddings_resnet_fsl # Path to load embeddings
  save_embeddings: true  # Save embeddings to disk
  embeddings_save_path: ./artifacts/CRC-VAL-HE-7K-splitted/embeddings_resnet_fsl # Path to save embeddings
  list_of_metrics:
    # - type: accuracy
    # - type: f1_score
    # - type: precision
    # - type: recall
  - type: map@k
    k_values: [1, 3, 5, 10]
  - type: precision@k
    k_values: [1, 3, 5, 10]
  - type: recall@k
    k_values: [1, 3, 5, 10]
  - type: accuracy@k
    k_values: [1, 3, 5, 10]

# Logging configuration
logging:
  log_file: ./logs.txt    # file to save logs
  log_level: INFO    # Set logging level (DEBUG, INFO, WARNING, ERROR)

metric_logging:
  tool: txt    # Tool to log metrics (txt, csv, mlflow, etc.)
# Output configuration
output:
  model_dir: ./artifacts/CRC-VAL-HE-7K-splitted # Directory to save model artifacts
  results_dir: ./local_experiments/CRC-VAL-HE-7K-splitted # Directory to save results


