# Paths and directories for training and testing data
data:
  dataset_type: StandardImageDataset    # Specify the dataset type (e.g., terumo, etc.)
  train_dir: datasets/final/glomerulo/train
  test_dir: datasets/final/glomerulo/test
  class_mapping: {Crescent: 0, Hypercellularity: 1, Membranous: 2, Normal: 3, Podocytopathy: 4,
    Sclerosis: 5}
  batch_size: 32 # Batch size for few-shot learning = 1
  num_workers: 3  # Number of workers to load the data
  suffle_train: false  # Shuffle the training data
  suffle_test: false
  support_set__:
    Crescent:
      - datasets/final/glomerulo/train/Crescent/Terumo_Crescent_AZAN/1409085.jpeg
      - datasets/final/glomerulo/train/Crescent/Terumo_Crescent_AZAN/1409141.jpeg
      - datasets/final/glomerulo/train/Crescent/Terumo_Crescent_AZAN/1409197.jpeg
      - datasets/final/glomerulo/train/Crescent/Terumo_Crescent_AZAN/1409254.jpeg
      - datasets/final/glomerulo/train/Crescent/Terumo_Crescent_AZAN/1409310.jpeg
    Hypercellularity:
      - datasets/final/glomerulo/train/Hypercellularity/Terumo_Hypercelularidade_AZAN/2303286.jpeg
      - datasets/final/glomerulo/train/Hypercellularity/Terumo_Hypercelularidade_AZAN/2303342.jpeg
      - datasets/final/glomerulo/train/Hypercellularity/Terumo_Hypercelularidade_AZAN/2303400.jpeg
      - datasets/final/glomerulo/train/Hypercellularity/Terumo_Hypercelularidade_AZAN/2303456.jpeg
      - datasets/final/glomerulo/train/Hypercellularity/Terumo_Hypercelularidade_AZAN/2303512.jpeg
    Membranous:
      - datasets/final/glomerulo/train/Membranous/Terumo_Membranous_AZAN/2316945.jpeg
      - datasets/final/glomerulo/train/Membranous/Terumo_Membranous_AZAN/2317001.jpeg
      - datasets/final/glomerulo/train/Membranous/Terumo_Membranous_AZAN/2317057.jpeg
      - datasets/final/glomerulo/train/Membranous/Terumo_Membranous_AZAN/2317113.jpeg
      - datasets/final/glomerulo/train/Membranous/Terumo_Membranous_AZAN/2317171.jpeg
    Normal:
      - datasets/final/glomerulo/train/Normal/Terumo_Normal_AZAN/2228493.jpeg
      - datasets/final/glomerulo/train/Normal/Terumo_Normal_AZAN/2228549.jpeg
      - datasets/final/glomerulo/train/Normal/Terumo_Normal_AZAN/2228607.jpeg
      - datasets/final/glomerulo/train/Normal/Terumo_Normal_AZAN/2228663.jpeg
      - datasets/final/glomerulo/train/Normal/Terumo_Normal_AZAN/2228719.jpeg
    Podocytopathy:
      - datasets/final/glomerulo/train/Podocytopathy/Terumo_Podocitopatia_AZAN/1793038.jpeg
      - datasets/final/glomerulo/train/Podocytopathy/Terumo_Podocitopatia_AZAN/1793094.jpeg
      - datasets/final/glomerulo/train/Podocytopathy/Terumo_Podocitopatia_AZAN/1794152.jpeg
      - datasets/final/glomerulo/train/Podocytopathy/Terumo_Podocitopatia_AZAN/1818119.jpeg
      - datasets/final/glomerulo/train/Podocytopathy/Terumo_Podocitopatia_AZAN/1818175.jpeg
    Sclerosis:
      - 'datasets/final/glomerulo/train/Sclerosis/Terumo_Sclerosis__HE/2021PC0275 (34).JPG'
      - 'datasets/final/glomerulo/train/Sclerosis/Terumo_Sclerosis__HE/2021PC0380 (21).jpg'
      - 'datasets/final/glomerulo/train/Sclerosis/Terumo_Sclerosis__HE/2021PC0440 (4).jpg'
      - 'datasets/final/glomerulo/train/Sclerosis/Terumo_Sclerosis__HE/2022PC0329 (12).jpg'
      - 'datasets/final/glomerulo/train/Sclerosis/Terumo_Sclerosis__HE/2022PC0329 (6).jpg'

# Model configuration
model:
  name: uni_fsl           # Example: You can set it to resnet18, resnet34, etc.
  experiment_name: uni_fsl_glomerulo_test             # Name of the experiment
  pretrained: true  # Use pre-trained weights
  num_classes: 6  # Number of classes in the dataset
  load_checkpoint: true  # Load a pre-trained model checkpoint
  checkpoint_path: 'artifacts/glomerulo/uni_fsl_glomerulo_uni_fsl_2025-04-19_18-43-39_checkpoint.pth'  # Path to the model checkpoint
  model_name: vit_large_patch16_224      # Specify the ViT model name
  n_way: 6 # Number of classes for few-shot learning
  k_shot: 5 # Suport set size per class
  q_queries: 6 # For few-shot learning, this will be the batch size
# total suport set size = n_way * q_shot
# total query set sizer (batch size) = n_way * k_queries
  # For example, if n_way=5 and q_shot=5, then total support set size = 5 * 5 = 25
  # For example, if n_way=5 and k_queries=6, then total query set size = 5 * 6 = 30


# Transformation configuration for image preprocessing
transform:
  resize: [224, 224]  # Resize images to 224x224
  normalize:
    mean: [0.485, 0.456, 0.406]  # Normalize mean for ImageNet
    std: [0.229, 0.224, 0.225]   # Normalize std for ImageNet
  to_tensor: true

testing:
  pipeline: fsl    # The pipeline to run (e.g., default, retrieval, etc.)
  load_embeddings: false  # Load embeddings from disk
  embeddings_path: ./artifacts/glomerulo/embeddings_uni_fsl             # Path to load embeddings
  save_embeddings: false  # Save embeddings to disk
  : ./artifacts/glomerulo/embeddings_uni_fsl             # Path to save embeddings


# Logging configuration
logging:
  log_file: ./logs.txt    # file to save logs
  log_level: INFO    # Set logging level (DEBUG, INFO, WARNING, ERROR)

metric_logging:
  tool: txt    # Tool to log metrics (txt, csv, mlflow, etc.)
# Output configuration
output:
  model_dir: ./artifacts/glomerulo    # Directory to save model artifacts
  results_dir: ./local_experiments/glomerulo    # Directory to save results




