data:
  batch_size: 32
  class_mapping:
    akiec: 0
    bcc: 1
    bkl: 2
    df: 3
    mel: 4
    nv: 5
    vasc: 6
  dataset_type: StandardImageDataset
  num_workers: 3
  suffle_test: false
  suffle_train: false
  test_dir: datasets/final/skin-cancer/retriv_test
  train_dir: datasets/final/skin-cancer/train
logging:
  log_file: ./logs.txt
  log_level: INFO
metric_logging:
  tool: txt
model:
  checkpoint_path: ''
  experiment_name: resnet50_skin-cancer
  load_checkpoint: false
  model_name: imagenet
  name: resnet50
  num_classes: 7
  pretrained: true
output:
  model_dir: ./artifacts/CRC-VAL-HE-7K
  results_dir: ./local_experiments/CRC-VAL-HE-7K
testing:
  embeddings_path: ./artifacts/CRC-VAL-HE-7K/embeddings_resnet50
  embeddings_save_path: ./artifacts/CRC-VAL-HE-7K/embeddings_resnet50
  list_of_metrics:
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: map@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: precision@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: recall@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: accuracy@k
  load_embeddings: false
  pipeline: default
  save_embeddings: true
transform:
  normalize:
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  resize:
  - 224
  - 224
  to_tensor: true
