# Paths and directories for training and testing data
data:
  dataset_type: StandardImageDataset    # Specify the dataset type (e.g., terumo, etc.)
  train_dir: datasets/final/glomerulo/train
  test_dir: datasets/final/glomerulo/test
  class_mapping: {Crescent: 0, Hypercellularity: 1, Membranous: 2, Normal: 3, Podocytopathy: 4,
    Sclerosis: 5}
  batch_size: 32
  num_workers: 3  # Number of workers to load the data
  suffle_test: false
  suffle_train: false

# Transformation configuration for image preprocessing
transform:
  test:
    resize: [224, 224]  # Resize images to 224x224
    normalize:
      mean: [0.485, 0.456, 0.406]  # Normalize mean for ImageNet
      std: [0.229, 0.224, 0.225]   # Normalize std for ImageNet
    to_tensor: true

# Model configuration
model:
  name: uni_fsl         # Example: You can set it to resnet18, resnet34, etc.
  experiment_name: uni_fsl_glomerulo         # Name of the experiment
  pretrained: true  # Use pre-trained weights
  num_classes: 6  # Number of classes in the dataset
  load_checkpoint: true   # Load a pre-trained model checkpoint
  checkpoint_path: ./artifacts/best-models/uni_fsl_glomerulo_uni_fsl_2025-05-27_14-28-01_checkpoint.pth # Path to the model checkpoint
  model_name: uni                        # Specify the ViT model name
  hidden_dim: 512
  embedding_dim: 128
  
testing:
  pipeline: default    # The pipeline to run (e.g., default, retrieval, etc.)
  load_embeddings: false  # Load embeddings from disk
  embeddings_path: ./artifacts/glomerulo/embeddings_uni_fsl         # Path to load embeddings
  save_embeddings: true  # Save embeddings to disk 
  normalize_embeddings: false  # Normalize embeddings to unit norm (L2 normalization)
  list_of_metrics:
    # - type: accuracy
    # - type: f1_score
    # - type: precision
    # - type: recall
  - type: map@k
    k_values: [1, 3, 6, 9, 12, 15]
    # - type: precision@k
    #   k_values: [1, 3, 5, 10, 15]
    # - type: recall@k
    #   k_values: [1, 3, 5, 10, 15]
    # - type: accuracy@k
    #   k_values: [1, 3, 5, 10, 15]

# Logging configuration
logging:
  log_file: ./logs.txt    # file to save logs
  log_level: INFO    # Set logging level (DEBUG, INFO, WARNING, ERROR)

metric_logging:
  tool: txt    # Tool to log metrics (txt, csv, mlflow, etc.)
# Output configuration
output:
  model_dir: ./artifacts/retr_fsl_train_test_glomerulo # Directory to save model artifacts
  results_dir: ./local_experiments/retr_fsl_train_test_glomerulo # Directory to save results


