# Paths and directories for training and testing data
data:
  train_dir: "datasets/final/terumo/train"
  test_dir: "datasets/final/terumo/test"
  class_mapping:
    Crescent: 0
    Hypercellularity: 1
    Membranous: 2
    Normal: 3
    Podocytopathy: 4
    Sclerosis: 5
  batch_size: 20
  num_workers: 3  # Number of workers to load the data
  dataset_type: "MixedTripletDataset"  
  
# Transformation configuration for image preprocessing
transform:
  resize: [224, 224]  # Resize images to 224x224
  normalize:
    mean: [0.485, 0.456, 0.406] # Normalize mean
    std: [0.229, 0.224, 0.225]   # Normalize std
  to_tensor: true  # Convert to tensor (default is true)

# Model configuration
model:
  name: "triplet_vit"  # Example: You can set it to resnet18, resnet34, etc.
  experiment_name: "triplet_vit"  # Name of the experiment
  embedding_size: 512  # Size of the embedding vector
  pretrained: true  # Use pre-trained weights
  num_classes: 6  # Number of classes in the dataset
  load_checkpoint: false  # Load a pre-trained model checkpoint
  checkpoint_path: ""  # Path to the model checkpoint

# Loss function configuration
loss:
  name: "adaptative_triplet"  # Specify the loss function (cross_entropy, etc.)

# Optimizer configuration
optimizer:
  name: "adam"  # Specify the optimizer (adam, sgd, etc.)
  lr: 0.001  # Learning rate
  weight_decay: 1e-4  # Weight decay for regularization

# Training configuration
training:
  pipeline: "train_triplet"  # The pipeline to run (e.g., train, finetune, etc.)
  epochs: 5  # Number of epochs to train
  lr_scheduler:
    name: "step_lr"  # Learning rate scheduler (step_lr, cosine_annealing, etc.)
    step_size: 10  # Step size for scheduler (for step_lr)
  list_of_metrics:
    - type: map@k
      k_values: [1, 3, 5, 10]
  val_retrieval:
    total_db_samples: 300
    total_query_samples: 60
    seed: 42

testing:
  pipeline: "default"  # The pipeline to run (e.g., default, retrieval, etc.)
  list_of_metrics:
    # - type: accuracy
    # - type: f1_score
    # - type: precision
    # - type: recall
    - type: map@k
      k_values: [1, 3, 5, 10]
    - type: precision@k
      k_values: [1, 3, 5, 10]
    - type: recall@k
      k_values: [1, 3, 5, 10]
    - type: accuracy@k
      k_values: [1, 3, 5, 10]
  load_embeddings: false  # Load embeddings from disk
  embeddings_path: "./artifacts/embeddings_triplet_vit"  # Path to load embeddings
  save_embeddings: true  # Save embeddings to disk
  : "./artifacts/embeddings_triplet_vit"  # Path to save embeddings

# Logging configuration
logging:
  log_file: "./logs.txt"  # file to save logs
  log_level: "INFO"  # Set logging level (DEBUG, INFO, WARNING, ERROR)

metric_logging:
  tool: "txt"  # Tool to log metrics (txt, csv, mlflow, etc.)
  
# Output configuration
output:
  model_dir: "./artifacts"  # Directory to save model artifacts
  results_dir: "."  # Directory to save results


