data:
  batch_size: 32
  class_mapping:
    akiec: 0
    bcc: 1
    bkl: 2
    df: 3
    mel: 4
    nv: 5
    vasc: 6
  dataset_type: StandardImageDataset
  num_workers: 3
  suffle_test: false
  suffle_train: false
  test_dir: datasets/final/skin-cancer-splitted/test
  train_dir: datasets/final/skin-cancer-splitted/train
logging:
  log_file: ./logs.txt
  log_level: INFO
metric_logging:
  tool: txt
model:
  checkpoint_path: ''
  experiment_name: dino_skin-cancer-splitted
  load_checkpoint: false
  model_name: vit_small_patch16_224_dino
  name: dino
  num_classes: 7
  pretrained: true
output:
  model_dir: ./artifacts/skin-cancer-splitted
  results_dir: ./local_experiments/skin-cancer-splitted
testing:
  embeddings_path: ./artifacts/skin-cancer-splitted/embeddings_dino
  embeddings_save_path: ./artifacts/skin-cancer-splitted/embeddings_dino
  list_of_metrics:
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: map@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: precision@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: recall@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: accuracy@k
  load_embeddings: false
  pipeline: default
  save_embeddings: true
transform:
  normalize:
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  resize:
  - 224
  - 224
  to_tensor: true
