data:
  batch_size: 32
  class_mapping:
    0_N: 0
    1_PB: 1
    2_UDH: 2
    3_FEA: 3
    4_ADH: 4
    5_DCIS: 5
    6_IC: 6
  dataset_type: StandardImageDataset
  num_workers: 3
  suffle_test: false
  suffle_train: false
  test_dir: datasets/final/bracs-resized/retriv_test
  train_dir: datasets/final/bracs-resized/train
logging:
  log_file: ./logs.txt
  log_level: INFO
metric_logging:
  tool: txt
model:
  checkpoint_path: ''
  experiment_name: uni_bracs-resized
  load_checkpoint: false
  model_name: vit_large_patch16_224
  name: uni
  num_classes: 7
  pretrained: true
output:
  model_dir: ./artifacts/bracs-resized
  results_dir: ./local_experiments/bracs-resized
testing:
  embeddings_path: ./artifacts/bracs-resized/embeddings_uni
  embeddings_save_path: ./artifacts/bracs-resized/embeddings_uni
  list_of_metrics:
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: map@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: precision@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: recall@k
  - k_values:
    - 1
    - 3
    - 5
    - 10
    type: accuracy@k
  load_embeddings: false
  pipeline: default
  save_embeddings: true
transform:
  normalize:
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  resize:
  - 224
  - 224
  to_tensor: true
