# Paths and directories for training and testing data
data:
  dataset_type: "TerumoImageDataset"  # Specify the dataset type (e.g., terumo, etc.)
  train_dir: "datasets/final/terumo/train"
  test_dir: "datasets/final/terumo/test"
  class_mapping:
    Crescent: 0
    Hypercellularity: 1
    Membranous: 2
    Normal: 3
    Podocytopathy: 4
    Sclerosis: 5
  batch_size: 32
  num_workers: 3  # Number of workers to load the data
  suffle_test: false
  suffle_train: false

# Transformation configuration for image preprocessing
transform:
  resize: [224, 224]  # Resize images to 224x224
  normalize:
    mean: [0.485, 0.456, 0.406]  # Normalize mean
    std: [0.229, 0.224, 0.225]   # Normalize std
  to_tensor: true  # Convert to tensor (default is true)

# Model configuration
model:
  name: "virchow2"  # Example: You can set it to resnet18, resnet34, etc.
  experiment_name: "virchow2_foundation_pathology"  # Name of the experiment
  pretrained: true  # Use pre-trained weights
  num_classes: 6  # Number of classes in the dataset
  load_checkpoint: false  # Load a pre-trained model checkpoint
  checkpoint_path: ""  # Path to the model checkpoint
  model_name: "hf-hub:paige-ai/Virchow2"  # Specify the ViT model name


testing:
  pipeline: "default"  # The pipeline to run (e.g., default, retrieval, etc.)
  load_embeddings: false  # Load embeddings from disk
  embeddings_path: "./artifacts/embeddings_clip"  # Path to load embeddings
  save_embeddings: true  # Save embeddings to disk
  embeddings_save_path: "./artifacts/embeddings_virchow2_foundation_pathology"  # Path to save embeddings
  list_of_metrics:
    # - type: accuracy
    # - type: f1_score
    # - type: precision
    # - type: recall
    - type: map@k
      k_values: [1, 3, 5, 10]
    - type: precision@k
      k_values: [1, 3, 5, 10]
    - type: recall@k
      k_values: [1, 3, 5, 10]
    - type: accuracy@k
      k_values: [1, 3, 5, 10]

# Logging configuration
logging:
  log_file: "./logs.txt"  # file to save logs
  log_level: "INFO"  # Set logging level (DEBUG, INFO, WARNING, ERROR)

metric_logging:
  tool: "txt"  # Tool to log metrics (txt, csv, mlflow, etc.)
  
# Output configuration
output:
  model_dir: "./artifacts"  # Directory to save model artifacts
  results_dir: "."  # Directory to save results


