# Paths and directories for training and testing data
data:
  dataset_type: "StandardImageDataset"  # Specify the dataset type (e.g., terumo, etc.)
  train_dir: "datasets/final/bracs-resized/train"
  test_dir: "datasets/final/bracs-resized/retriv_test"
  class_mapping:
    0_N: 0
    1_PB: 1
    2_UDH: 2
    3_FEA: 3
    4_ADH: 4
    5_DCIS: 5
    6_IC: 6
  batch_size: 64
  num_workers: 3  # Number of workers to load the data
  suffle_test: false
  suffle_train: false

# Transformation configuration for image preprocessing
transform:
  resize: [224, 224]  # Resize images to 224x224
  normalize:
    mean: [0.485, 0.456, 0.406]  # Normalize mean for ImageNet
    std: [0.229, 0.224, 0.225]   # Normalize std for ImageNet
  to_tensor: true  # Convert to tensor (default is true)

# Model configuration
model:
  name: "<model_name>"  # Example: You can set it to resnet18, resnet34, etc.
  experiment_name: "<model_name>_<dataset>"  # Name of the experiment
  pretrained: true  # Use pre-trained weights
  num_classes: 7  # Number of classes in the dataset
  load_checkpoint: false  # Load a pre-trained model checkpoint
  checkpoint_path: ""  # Path to the model checkpoint
  model_name: "<pretreined_model_name>"  # Specify the ViT model name


testing:
  pipeline: "default"  # The pipeline to run (e.g., default, retrieval, etc.)
  load_embeddings: false  # Load embeddings from disk
  embeddings_path: "./artifacts/<dataset>/embeddings_<model_name>"  # Path to load embeddings
  save_embeddings: true  # Save embeddings to disk
  : "./artifacts/<dataset>/embeddings_<model_name>"  # Path to save embeddings
  normalize_embeddings: false  # Normalize embeddings to unit norm (L2 normalization)
  list_of_metrics:
    # - type: accuracy
    # - type: f1_score
    # - type: precision
    # - type: recall
    - type: map@k
      k_values: [1, 3, 6, 9, 12, 15]
    # - type: precision@k
    #   k_values: [1, 3, 5, 10, 15]
    # - type: recall@k
    #   k_values: [1, 3, 5, 10, 15]
    # - type: accuracy@k
    #   k_values: [1, 3, 5, 10, 15]

# Logging configuration
logging:
  log_file: "./logs.txt"  # file to save logs
  log_level: "INFO"  # Set logging level (DEBUG, INFO, WARNING, ERROR)

metric_logging:
  tool: "txt"  # Tool to log metrics (txt, csv, mlflow, etc.)
  
# Output configuration
output:
  model_dir: "./artifacts/<dataset>"  # Directory to save model artifacts
  results_dir: "./local_experiments/<dataset>"  # Directory to save results


